### ISSUE TITLE
No support for AWS::NoValue

### ISSUE THREAD

**Issue by lox** [drrb/cfoo#6]
Should this work?

```
SpotPrice: !If [ !Equal [ $(SpotPrice), "0", ], $(AWS::NoValue), $(SpotPrice) ]
```

I get:
(./buildkite-elastic.yml): found unexpected ':' while scanning a plain scalar at line 144 column 55

**Comment by agperson** [comment]
It will work with quoting, for example this compiles:
```yaml
---
Parameters:
  SpotPrice:
    Type: String
Resources:
  MyInstane:
    Properties:
      SpotPrice: !If [ !Equals [ $(SpotPrice), "0" ], "$(AWS:NoValue)", $(SpotPrice) ]
```
